# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
'''{r}
data <- read.csv("activity.csv", colClasses = c("numeric", "Date", "numeric"))
data1<-data[!is.na(data$steps),]
'''

## What is mean total number of steps taken per day?
'''{r}
histdata<-aggregate(data1$steps,by=list(data1$date),FUN=sum)
hist(histdata$x, main = "total number of steps taken per day", xlab="steps", ylab="Frequency")
mean(histdata$x)
median(histdata$x)
'''

## What is the average daily activity pattern?
'''{r}
timedata<-aggregate(data1$steps, by=list(data1$interval),FUN=sum)
plot(x=timedata$Group.1, y=timedata$x, type="l", main="average steps taken in a 5 minutes' period", xlab="timeperiod", ylab="steps")
index<-which.max(timedata$x)
print(timedata$x[index])
print(timedata$Group.1[index])
'''

## Imputing missing values
'''{r}
print(length(is.na(data$steps)))
dataImputed<-data
set.seed(0) # must be set as the imputation method "sample" is using random numbers
dataImputed[is.na(data$steps),"steps"]<-mice.impute.sample(data$steps, !is.na(data$steps))
histdata2<-aggregate(dataImputed$steps,by=list(dataImputed$date),FUN=sum)
hist(histdata2$x, main = "total number of steps taken per day (with imputed data)", xlab="steps", ylab="Frequency")
'''

## Are there differences in activity patterns between weekdays and weekends?
'''{r}
histdata$wd<-weekdays(histdata$Group.1)
weekend<-(histdata$wd == "Saturday" | histdata$wd == "Sunday")
plot(histdata$Group.1,histdata$x,type="n", main="step taken on weekdays/weekends", xlab="date", ylab="")
lines(histdata$Group.1[weekend],histdata$x[weekend], col="red")
lines(histdata$Group.1[!weekend],histdata$x[!weekend], col="blue")
text(x=as.Date("2012-11-22"),y=20000, labels="weekdays", col="blue", pos=2)
text(x=as.Date("2012-11-15"),y=15000, labels="weekdays", col="red", pos=2)
'''
